/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: dante6686 (https://sketchfab.com/dante6686)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/alien-planet-94811bf33a4c4a5992aeb7b5d3468ac8
title: Alien planet
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/alien.gltf')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group position={[0.24, 0.22, 0.01]} rotation={[-1.57, 0, -Math.PI / 2]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group name="Crystal_10" position={[0, 1.55, 0]} scale={[0.32, 0.88, 0.32]}>
            <mesh geometry={nodes.Object_22.geometry} material={nodes.Object_22.material} />
          </group>
          <mesh geometry={nodes.Object_4.geometry} material={materials.Dirt} />
          <group position={[-2.45, 0.48, 1.42]} rotation={[0.3, 0.12, 0.17]} scale={[0.38, 0.38, 0.38]}>
            <mesh geometry={nodes.Object_6.geometry} material={nodes.Object_6.material} />
          </group>
          <group position={[-3.3, 0.89, -1.16]} rotation={[1.56, -0.05, 3.11]} scale={0.38}>
            <mesh geometry={nodes.Object_8.geometry} material={nodes.Object_8.material} />
          </group>
          <group position={[0.54, 0.96, -3.46]} rotation={[0.38, 0.64, -0.02]} scale={0.38}>
            <mesh geometry={nodes.Object_10.geometry} material={nodes.Object_10.material} />
          </group>
          <group position={[0.83, 0.64, 2.65]} rotation={[0.61, 0.29, 0.17]} scale={[0.38, 0.38, 0.38]}>
            <mesh geometry={nodes.Object_12.geometry} material={nodes.Object_12.material} />
          </group>
          <group position={[-0.52, 0.45, -2.11]} scale={0.27}>
            <mesh geometry={nodes.Object_14.geometry} material={nodes.Object_14.material} />
          </group>
          <group position={[-2.06, 0.71, -0.7]} scale={0.22}>
            <mesh geometry={nodes.Object_16.geometry} material={nodes.Object_16.material} />
          </group>
          <group position={[-0.87, 1.25, 1.43]} scale={0.22}>
            <mesh geometry={nodes.Object_18.geometry} material={nodes.Object_18.material} />
          </group>
          <group position={[2.1, 1.06, 2.48]} scale={0.22}>
            <mesh geometry={nodes.Object_20.geometry} material={nodes.Object_20.material} />
          </group>
          <group position={[-0.64, 0.24, 2.96]} rotation={[0.71, 0.5, -Math.PI / 2]} scale={[0.7, 0.7, 0.7]}>
            <mesh geometry={nodes.Object_24.geometry} material={nodes.Object_24.material} />
          </group>
          <group position={[1.08, 0.37, 3.02]} rotation={[1.82, -0.05, -Math.PI / 2]} scale={[0.35, 0.35, 0.35]}>
            <mesh geometry={nodes.Object_26.geometry} material={nodes.Object_26.material} />
          </group>
          <group position={[1.99, 0.16, 3.22]} rotation={[1.92, -0.19, -Math.PI / 2]} scale={[0.83, 0.83, 0.83]}>
            <mesh geometry={nodes.Object_28.geometry} material={nodes.Object_28.material} />
          </group>
          <group position={[-0.13, 0.5, 0.22]} rotation={[2.27, -1.08, -Math.PI / 2]} scale={[0.47, 0.47, 0.47]}>
            <mesh geometry={nodes.Object_30.geometry} material={nodes.Object_30.material} />
          </group>
          <group position={[-1.41, 0.38, -1.63]} rotation={[1.44, 0.8, -Math.PI / 2]} scale={[0.78, 0.78, 0.78]}>
            <mesh geometry={nodes.Object_32.geometry} material={nodes.Object_32.material} />
          </group>
          <group position={[0.65, 0.19, -1.47]} rotation={[0.72, 0, -Math.PI / 2]} scale={[0.86, 0.86, 0.86]}>
            <mesh geometry={nodes.Object_34.geometry} material={nodes.Object_34.material} />
          </group>
          <group position={[-0.54, 0.43, -3.53]} rotation={[1.08, -0.04, -Math.PI / 2]} scale={[0.5, 0.5, 0.5]}>
            <mesh geometry={nodes.Object_36.geometry} material={nodes.Object_36.material} />
          </group>
          <group position={[0, 0.44, -3.03]} rotation={[1.64, -0.09, -Math.PI / 2]} scale={0.51}>
            <mesh geometry={nodes.Object_38.geometry} material={nodes.Object_38.material} />
          </group>
          <group position={[4.36, -0.1, 0.51]} rotation={[1.48, 0.09, -Math.PI / 2]} scale={[0.53, 0.53, 0.53]}>
            <mesh geometry={nodes.Object_40.geometry} material={nodes.Object_40.material} />
          </group>
          <group position={[3.59, -0.16, 0.34]} rotation={[1.69, 0.33, -Math.PI / 2]} scale={[0.75, 0.75, 0.75]}>
            <mesh geometry={nodes.Object_42.geometry} material={nodes.Object_42.material} />
          </group>
          <group position={[3.1, 0.02, -2.65]} rotation={[0.86, -0.36, -Math.PI / 2]} scale={[0.86, 0.86, 0.86]}>
            <mesh geometry={nodes.Object_44.geometry} material={nodes.Object_44.material} />
          </group>
          <group position={[1.87, 0.09, -3.96]} rotation={[1.21, -0.18, -Math.PI / 2]} scale={[0.37, 0.37, 0.37]}>
            <mesh geometry={nodes.Object_46.geometry} material={nodes.Object_46.material} />
          </group>
          <group position={[0.16, 0.31, -4.09]} rotation={[1.15, -0.14, -Math.PI / 2]} scale={[0.64, 0.64, 0.64]}>
            <mesh geometry={nodes.Object_48.geometry} material={nodes.Object_48.material} />
          </group>
          <group position={[-4.14, 0.15, 0.14]} rotation={[1.41, 0.31, -Math.PI / 2]} scale={[0.7, 0.7, 0.7]}>
            <mesh geometry={nodes.Object_50.geometry} material={nodes.Object_50.material} />
          </group>
          <group position={[0.4, 0.22, 2.98]} rotation={[0.96, -0.11, -Math.PI / 2]} scale={[0.72, 0.72, 0.72]}>
            <mesh geometry={nodes.Object_52.geometry} material={nodes.Object_52.material} />
          </group>
          <group position={[-2.62, 0.63, 1.22]} rotation={[0.56, 0.03, -Math.PI / 2]} scale={[0.31, 0.31, 0.31]}>
            <mesh geometry={nodes.Object_54.geometry} material={nodes.Object_54.material} />
          </group>
          <group position={[-1.6, 0.58, 1.6]} rotation={[1.55, -0.54, -Math.PI / 2]} scale={[0.69, 0.69, 0.69]}>
            <mesh geometry={nodes.Object_56.geometry} material={nodes.Object_56.material} />
          </group>
          <group position={[-2.26, 0.75, 0.43]} rotation={[1.49, 0.1, -Math.PI / 2]} scale={[0.8, 0.8, 0.8]}>
            <mesh geometry={nodes.Object_58.geometry} material={nodes.Object_58.material} />
          </group>
          <group position={[-0.71, 0.65, 0.81]} rotation={[1.62, -0.11, -Math.PI / 2]} scale={[0.43, 0.43, 0.43]}>
            <mesh geometry={nodes.Object_60.geometry} material={nodes.Object_60.material} />
          </group>
          <group position={[-0.63, 0.49, 0.31]} rotation={[0.32, -0.38, -Math.PI / 2]} scale={[0.55, 0.55, 0.55]}>
            <mesh geometry={nodes.Object_62.geometry} material={nodes.Object_62.material} />
          </group>
          <group position={[0.63, 0.45, 0.24]} rotation={[1.46, -0.06, -Math.PI / 2]} scale={[0.62, 0.62, 0.62]}>
            <mesh geometry={nodes.Object_64.geometry} material={nodes.Object_64.material} />
          </group>
          <group position={[1.57, 0.41, 1.11]} rotation={[2.65, 0.44, -Math.PI / 2]} scale={[0.68, 0.68, 0.68]}>
            <mesh geometry={nodes.Object_66.geometry} material={nodes.Object_66.material} />
          </group>
          <group position={[-0.82, 0.25, -0.95]} rotation={[0.59, 0.33, -Math.PI / 2]} scale={[0.55, 0.55, 0.55]}>
            <mesh geometry={nodes.Object_68.geometry} material={nodes.Object_68.material} />
          </group>
          <group position={[2.55, 0.19, -0.48]} rotation={[1.53, -0.57, -Math.PI / 2]} scale={[0.89, 0.89, 0.89]}>
            <mesh geometry={nodes.Object_70.geometry} material={nodes.Object_70.material} />
          </group>
          <group position={[-3.01, 0.36, -1.1]} rotation={[2.12, 0.15, -Math.PI / 2]} scale={[0.52, 0.52, 0.52]}>
            <mesh geometry={nodes.Object_72.geometry} material={nodes.Object_72.material} />
          </group>
          <group position={[-1.43, 0.39, -1.44]} rotation={[1.49, 0.61, -Math.PI / 2]} scale={[0.47, 0.47, 0.47]}>
            <mesh geometry={nodes.Object_74.geometry} material={nodes.Object_74.material} />
          </group>
          <group position={[-0.36, 0.23, -1.23]} rotation={[1.39, 0.88, -Math.PI / 2]} scale={[0.52, 0.52, 0.52]}>
            <mesh geometry={nodes.Object_76.geometry} material={nodes.Object_76.material} />
          </group>
          <group position={[-0.12, 0.25, -1.6]} rotation={[0.47, 0.38, -Math.PI / 2]} scale={[0.33, 0.33, 0.33]}>
            <mesh geometry={nodes.Object_78.geometry} material={nodes.Object_78.material} />
          </group>
          <group position={[1.06, 0.14, -1.47]} rotation={[0.53, -0.13, -Math.PI / 2]} scale={0.41}>
            <mesh geometry={nodes.Object_80.geometry} material={nodes.Object_80.material} />
          </group>
          <group position={[0.27, 0.23, -1.62]} rotation={[1.09, -0.86, -Math.PI / 2]} scale={[0.65, 0.65, 0.65]}>
            <mesh geometry={nodes.Object_82.geometry} material={nodes.Object_82.material} />
          </group>
          <group position={[-1.35, 0.35, -3.41]} rotation={[1.3, 0.04, -Math.PI / 2]} scale={[0.61, 0.61, 0.61]}>
            <mesh geometry={nodes.Object_84.geometry} material={nodes.Object_84.material} />
          </group>
          <group position={[2.25, 0.15, -2.77]} rotation={[0.56, 0.04, -Math.PI / 2]} scale={[0.86, 0.86, 0.86]}>
            <mesh geometry={nodes.Object_86.geometry} material={nodes.Object_86.material} />
          </group>
          <group position={[3.69, 0.07, 2]} rotation={[1.22, 0.43, -Math.PI / 2]} scale={[0.37, 0.37, 0.37]}>
            <mesh geometry={nodes.Object_88.geometry} material={nodes.Object_88.material} />
          </group>
          <group position={[3.55, -0.12, -0.26]} rotation={[2.03, -0.6, -Math.PI / 2]} scale={[0.48, 0.48, 0.48]}>
            <mesh geometry={nodes.Object_90.geometry} material={nodes.Object_90.material} />
          </group>
          <group position={[-2.11, 0.13, -3.68]} rotation={[1.39, -0.22, -Math.PI / 2]} scale={[0.49, 0.49, 0.49]}>
            <mesh geometry={nodes.Object_92.geometry} material={nodes.Object_92.material} />
          </group>
          <group position={[-4.04, 0.09, -0.29]} rotation={[1.19, 0.24, -Math.PI / 2]} scale={[0.76, 0.76, 0.76]}>
            <mesh geometry={nodes.Object_94.geometry} material={nodes.Object_94.material} />
          </group>
          <group position={[-4.48, 0.14, 0.65]} rotation={[1.5, 0.19, -Math.PI / 2]} scale={[0.56, 0.56, 0.56]}>
            <mesh geometry={nodes.Object_96.geometry} material={nodes.Object_96.material} />
          </group>
          <group position={[-3.85, 0.22, 1.44]} rotation={[1.81, 0.28, -Math.PI / 2]} scale={[0.49, 0.49, 0.49]}>
            <mesh geometry={nodes.Object_98.geometry} material={nodes.Object_98.material} />
          </group>
          <group position={[-3.3, 0.08, 2.2]} rotation={[1.66, 0.47, -Math.PI / 2]} scale={[0.54, 0.54, 0.54]}>
            <mesh geometry={nodes.Object_100.geometry} material={nodes.Object_100.material} />
          </group>
          <group position={[-2.53, 0.68, 0.25]} rotation={[1.46, 0.26, -Math.PI / 2]} scale={[0.03, 0.03, 0.03]}>
            <mesh geometry={nodes.Object_102.geometry} material={nodes.Object_102.material} />
          </group>
          <group position={[-0.38, 0.58, 1.09]} rotation={[1.68, -0.1, -Math.PI / 2]} scale={[0.03, 0.03, 0.03]}>
            <mesh geometry={nodes.Object_104.geometry} material={nodes.Object_104.material} />
          </group>
          <group position={[1.32, 0.48, 0.76]} rotation={[1.59, 0.05, -Math.PI / 2]} scale={[0.05, 0.05, 0.05]}>
            <mesh geometry={nodes.Object_106.geometry} material={nodes.Object_106.material} />
          </group>
          <group position={[2.84, 0.13, -0.73]} rotation={[1.64, 0.1, -Math.PI / 2]} scale={[0.05, 0.05, 0.05]}>
            <mesh geometry={nodes.Object_108.geometry} material={nodes.Object_108.material} />
          </group>
          <group position={[3.12, 0.06, -2.44]} rotation={[1.46, -0.19, -Math.PI / 2]} scale={[0.04, 0.04, 0.04]}>
            <mesh geometry={nodes.Object_110.geometry} material={nodes.Object_110.material} />
          </group>
          <group position={[-1.34, 0.08, 4.09]} rotation={[1.83, 0.07, -Math.PI / 2]} scale={[0.05, 0.05, 0.05]}>
            <mesh geometry={nodes.Object_112.geometry} material={nodes.Object_112.material} />
          </group>
          <group position={[0.27, 0.33, 3.39]} rotation={[1.77, -0.01, -Math.PI / 2]} scale={[0.04, 0.04, 0.04]}>
            <mesh geometry={nodes.Object_114.geometry} material={nodes.Object_114.material} />
          </group>
          <group position={[4.37, -0.2, -0.03]} rotation={[1.54, -0.13, -Math.PI / 2]} scale={[0.05, 0.05, 0.05]}>
            <mesh geometry={nodes.Object_116.geometry} material={nodes.Object_116.material} />
          </group>
          <group position={[2.3, 0.23, 2.84]} rotation={[1.86, -0.21, -Math.PI / 2]} scale={[0.04, 0.04, 0.04]}>
            <mesh geometry={nodes.Object_118.geometry} material={nodes.Object_118.material} />
          </group>
          <group position={[2.17, 0.28, -0.26]} rotation={[1.51, -0.18, -Math.PI / 2]} scale={[0.05, 0.05, 0.05]}>
            <mesh geometry={nodes.Object_120.geometry} material={nodes.Object_120.material} />
          </group>
          <group position={[2.02, 0.2, -3.14]} rotation={[1.58, -0.51, -Math.PI / 2]} scale={[0.03, 0.03, 0.03]}>
            <mesh geometry={nodes.Object_122.geometry} material={nodes.Object_122.material} />
          </group>
          <group position={[-2.83, 0.02, 3.05]} rotation={[1.79, 0.2, -Math.PI / 2]} scale={[0.03, 0.03, 0.03]}>
            <mesh geometry={nodes.Object_124.geometry} material={nodes.Object_124.material} />
          </group>
          <group position={[-1.77, 0.17, 3.34]} rotation={[2.48, 0.15, -Math.PI / 2]} scale={[0.03, 0.03, 0.03]}>
            <mesh geometry={nodes.Object_126.geometry} material={nodes.Object_126.material} />
          </group>
          <group position={[0.12, 0.2, 3.83]} rotation={[2.33, -0.15, -Math.PI / 2]} scale={[0.05, 0.05, 0.05]}>
            <mesh geometry={nodes.Object_128.geometry} material={nodes.Object_128.material} />
          </group>
          <group position={[3.96, -0.07, 0.71]} rotation={[1.22, -0.08, -Math.PI / 2]} scale={[0.05, 0.05, 0.05]}>
            <mesh geometry={nodes.Object_130.geometry} material={nodes.Object_130.material} />
          </group>
          <group position={[4, -0.14, -0.03]} rotation={[1.62, -0.17, -Math.PI / 2]} scale={[0.04, 0.04, 0.04]}>
            <mesh geometry={nodes.Object_132.geometry} material={nodes.Object_132.material} />
          </group>
          <group position={[-4.59, -0.11, -1.04]} rotation={[1.77, 0.21, -Math.PI / 2]} scale={[0.03, 0.03, 0.03]}>
            <mesh geometry={nodes.Object_134.geometry} material={nodes.Object_134.material} />
          </group>
          <group position={[1.3, 0.8, 3.42]} rotation={[-1.9, 0, -2]} scale={[0.23, 0.23, 0.23]}>
            <mesh geometry={nodes.Object_136.geometry} material={nodes.Object_136.material} />
          </group>
          <group position={[1.01, 1.25, 3.02]} rotation={[2.15, 0, -2.46]} scale={0.19}>
            <mesh geometry={nodes.Object_138.geometry} material={nodes.Object_138.material} />
          </group>
          <group position={[0.96, 0.76, 2.65]} rotation={[2.37, 0, -2.62]} scale={[0.25, 0.25, 0.25]}>
            <mesh geometry={nodes.Object_140.geometry} material={nodes.Object_140.material} />
          </group>
          <group position={[1.04, 0.97, 2.8]} rotation={[2.25, 0, -2.57]} scale={[0.2, 0.2, 0.2]}>
            <mesh geometry={nodes.Object_142.geometry} material={nodes.Object_142.material} />
          </group>
          <group position={[1.23, 0.85, 2.88]} rotation={[2.36, 0, -2.38]} scale={[0.24, 0.24, 0.24]}>
            <mesh geometry={nodes.Object_144.geometry} material={nodes.Object_144.material} />
          </group>
          <group position={[1.47, 0.6, 2.8]} rotation={[2.98, 0, -2.15]} scale={[0.25, 0.25, 0.25]}>
            <mesh geometry={nodes.Object_146.geometry} material={nodes.Object_146.material} />
          </group>
          <group position={[1.09, 1.15, 3.5]} rotation={[-2.08, 0, -2.08]} scale={[0.21, 0.21, 0.21]}>
            <mesh geometry={nodes.Object_148.geometry} material={nodes.Object_148.material} />
          </group>
          <group position={[0.79, 2.74, 4.02]} rotation={[-2.59, 0, -1.83]} scale={[0.21, 0.21, 0.21]}>
            <mesh geometry={nodes.Object_150.geometry} material={nodes.Object_150.material} />
          </group>
          <group position={[0.74, 2.92, 4.44]} rotation={[-1.24, 0, -2.11]} scale={[0.21, 0.21, 0.21]}>
            <mesh geometry={nodes.Object_152.geometry} material={nodes.Object_152.material} />
          </group>
          <group position={[0.57, 2.66, 4.37]} rotation={[-0.74, 0, -2.59]} scale={[0.24, 0.24, 0.24]}>
            <mesh geometry={nodes.Object_154.geometry} material={nodes.Object_154.material} />
          </group>
          <group position={[0.4, 2.59, 4.39]} rotation={[-0.95, 0, -3.11]} scale={[0.25, 0.25, 0.25]}>
            <mesh geometry={nodes.Object_156.geometry} material={nodes.Object_156.material} />
          </group>
          <group position={[0.5, 2.92, 4.59]} rotation={[-1.69, 0, 3.07]} scale={[0.19, 0.19, 0.19]}>
            <mesh geometry={nodes.Object_158.geometry} material={nodes.Object_158.material} />
          </group>
          <group position={[0.64, 0.93, 2.67]} rotation={[2.38, 0, 2.69]} scale={[0.22, 0.22, 0.22]}>
            <mesh geometry={nodes.Object_160.geometry} material={nodes.Object_160.material} />
          </group>
          <group position={[1.09, 0.73, 2.72]} rotation={[2.47, 0, -2.55]} scale={[0.23, 0.23, 0.23]}>
            <mesh geometry={nodes.Object_162.geometry} material={nodes.Object_162.material} />
          </group>
          <group position={[1.49, 0.58, 2.78]} rotation={[2.95, 0, -2.17]} scale={[0.23, 0.23, 0.23]}>
            <mesh geometry={nodes.Object_164.geometry} material={nodes.Object_164.material} />
          </group>
          <group position={[1.51, 0.54, 2.77]} rotation={[2.97, 0, -2.1]} scale={[0.18, 0.18, 0.18]}>
            <mesh geometry={nodes.Object_166.geometry} material={nodes.Object_166.material} />
          </group>
          <group position={[1.57, 0.26, 2.84]} rotation={[2.88, 0, -2.07]} scale={[0.23, 0.23, 0.23]}>
            <mesh geometry={nodes.Object_168.geometry} material={nodes.Object_168.material} />
          </group>
          <group position={[-2.97, 1.64, 1.19]} rotation={[2.4, 0, 2.8]} scale={0.14}>
            <mesh geometry={nodes.Object_170.geometry} material={nodes.Object_170.material} />
          </group>
          <group position={[-3.16, 1.59, 1.37]} rotation={[2.11, 0, 2.36]} scale={0.14}>
            <mesh geometry={nodes.Object_172.geometry} material={nodes.Object_172.material} />
          </group>
          <group position={[-3.22, 1.74, 1.57]} rotation={[2.73, 0, 2.6]} scale={[0.17, 0.17, 0.17]}>
            <mesh geometry={nodes.Object_174.geometry} material={nodes.Object_174.material} />
          </group>
          <group position={[-3.14, 1.8, 1.65]} rotation={[2.81, 0, 2.69]} scale={[0.16, 0.16, 0.16]}>
            <mesh geometry={nodes.Object_176.geometry} material={nodes.Object_176.material} />
          </group>
          <group position={[-3.08, 1.87, 1.77]} rotation={[2.93, 0, 2.73]} scale={[0.16, 0.16, 0.16]}>
            <mesh geometry={nodes.Object_178.geometry} material={nodes.Object_178.material} />
          </group>
          <group position={[-2.82, 1.83, 1.79]} rotation={[2.77, 0, -2.77]} scale={[0.17, 0.17, 0.17]}>
            <mesh geometry={nodes.Object_180.geometry} material={nodes.Object_180.material} />
          </group>
          <group position={[-2.77, 1.91, 2.11]} rotation={[-3.05, 0, -2.88]} scale={[0.16, 0.16, 0.16]}>
            <mesh geometry={nodes.Object_182.geometry} material={nodes.Object_182.material} />
          </group>
          <group position={[-2.88, 1.97, 2.12]} rotation={[-3.09, 0, -3.05]} scale={[0.17, 0.17, 0.17]}>
            <mesh geometry={nodes.Object_184.geometry} material={nodes.Object_184.material} />
          </group>
          <group position={[-2.73, 1.88, 2.07]} rotation={[-3.1, 0, -2.76]} scale={[0.16, 0.16, 0.16]}>
            <mesh geometry={nodes.Object_186.geometry} material={nodes.Object_186.material} />
          </group>
          <group position={[-3.48, 1.31, -0.29]} rotation={[-2.72, 0, 2.92]} scale={[0.24, 0.24, 0.24]}>
            <mesh geometry={nodes.Object_188.geometry} material={nodes.Object_188.material} />
          </group>
          <group position={[-2.75, 1.09, -1.93]} rotation={[3.05, 0, -2.61]} scale={[0.25, 0.25, 0.25]}>
            <mesh geometry={nodes.Object_190.geometry} material={nodes.Object_190.material} />
          </group>
          <group position={[-2.31, 1.01, -1.99]} rotation={[3, 0, -3.02]} scale={[0.2, 0.2, 0.2]}>
            <mesh geometry={nodes.Object_192.geometry} material={nodes.Object_192.material} />
          </group>
          <group position={[-2.41, 0.85, -2.33]} rotation={[2.86, 0, -3.08]} scale={[0.19, 0.19, 0.19]}>
            <mesh geometry={nodes.Object_194.geometry} material={nodes.Object_194.material} />
          </group>
          <group position={[-3.12, 1.27, -0.24]} rotation={[-2.6, 0, -3.05]} scale={[0.2, 0.2, 0.2]}>
            <mesh geometry={nodes.Object_196.geometry} material={nodes.Object_196.material} />
          </group>
          <group position={[-3.33, 1.34, -0.47]} rotation={[-2.86, 0, 3.05]} scale={[0.24, 0.24, 0.24]}>
            <mesh geometry={nodes.Object_198.geometry} material={nodes.Object_198.material} />
          </group>
          <group position={[-2.63, 2.19, -0.78]} rotation={[2.7, 0, -2.59]} scale={[0.23, 0.23, 0.23]}>
            <mesh geometry={nodes.Object_200.geometry} material={nodes.Object_200.material} />
          </group>
          <group position={[-3.23, 1.21, -0.13]} rotation={[-2.38, 0, -3.13]} scale={[0.23, 0.23, 0.23]}>
            <mesh geometry={nodes.Object_202.geometry} material={nodes.Object_202.material} />
          </group>
          <group position={[1.17, 2.06, -3.15]} rotation={[-2.98, 0, -1.91]} scale={[0.23, 0.23, 0.23]}>
            <mesh geometry={nodes.Object_204.geometry} material={nodes.Object_204.material} />
          </group>
          <group position={[0.74, 2.68, -2.79]} rotation={[3.12, 0, -1.87]} scale={[0.19, 0.19, 0.19]}>
            <mesh geometry={nodes.Object_206.geometry} material={nodes.Object_206.material} />
          </group>
          <group position={[-0.16, 2.76, -2.25]} rotation={[-2.36, 0, 3.11]} scale={[0.25, 0.25, 0.25]}>
            <mesh geometry={nodes.Object_208.geometry} material={nodes.Object_208.material} />
          </group>
          <group position={[-0.46, 3.01, -2.89]} rotation={[-2.78, 0, 2.77]} scale={[0.2, 0.2, 0.2]}>
            <mesh geometry={nodes.Object_210.geometry} material={nodes.Object_210.material} />
          </group>
          <group position={[0.57, 3.08, -2.95]} rotation={[2.6, 0, -2.48]} scale={[0.24, 0.24, 0.24]}>
            <mesh geometry={nodes.Object_212.geometry} material={nodes.Object_212.material} />
          </group>
          <group position={[0.49, 2.6, -3.53]} rotation={[2.36, 0, -2.56]} scale={[0.25, 0.25, 0.25]}>
            <mesh geometry={nodes.Object_214.geometry} material={nodes.Object_214.material} />
          </group>
          <group position={[1.09, 2.2, -3.17]} rotation={[2.99, 0, -2.55]} scale={[0.21, 0.21, 0.21]}>
            <mesh geometry={nodes.Object_216.geometry} material={nodes.Object_216.material} />
          </group>
          <group position={[0.61, 2.35, -3.31]} rotation={[2.22, 0, -2.1]} scale={[0.21, 0.21, 0.21]}>
            <mesh geometry={nodes.Object_218.geometry} material={nodes.Object_218.material} />
          </group>
          <group position={[0.63, 2.35, -3.17]} rotation={[2.26, 0, -2.06]} scale={0.21}>
            <mesh geometry={nodes.Object_220.geometry} material={nodes.Object_220.material} />
          </group>
          <group position={[0.59, 2.26, -3.49]} rotation={[2.24, 0, -2.21]} scale={[0.24, 0.24, 0.24]}>
            <mesh geometry={nodes.Object_222.geometry} material={nodes.Object_222.material} />
          </group>
          <group position={[-0.56, 2.94, -2.81]} rotation={[-3.03, 0, 2.68]} scale={[0.25, 0.25, 0.25]}>
            <mesh geometry={nodes.Object_224.geometry} material={nodes.Object_224.material} />
          </group>
          <group position={[0.03, 2.94, -2.49]} rotation={[-2.57, 0, 3.08]} scale={[0.19, 0.19, 0.19]}>
            <mesh geometry={nodes.Object_226.geometry} material={nodes.Object_226.material} />
          </group>
          <group position={[0, 3.17, -3.08]} rotation={[2.77, 0, -3.04]} scale={[0.22, 0.22, 0.22]}>
            <mesh geometry={nodes.Object_228.geometry} material={nodes.Object_228.material} />
          </group>
          <group position={[-0.4, 3.04, -3.11]} rotation={[2.54, 0, 2.59]} scale={[0.23, 0.23, 0.23]}>
            <mesh geometry={nodes.Object_230.geometry} material={nodes.Object_230.material} />
          </group>
          <group position={[-1.01, 2.65, -2.36]} rotation={[-2.8, 0, 2.6]} scale={[0.23, 0.23, 0.23]}>
            <mesh geometry={nodes.Object_232.geometry} material={nodes.Object_232.material} />
          </group>
          <group position={[-1.27, 2.49, -2.21]} rotation={[-2.51, 0, 2.57]} scale={[0.18, 0.18, 0.18]}>
            <mesh geometry={nodes.Object_234.geometry} material={nodes.Object_234.material} />
          </group>
          <group position={[-1.25, 2.41, -2.15]} rotation={[-2.41, 0, 2.56]} scale={[0.23, 0.23, 0.23]}>
            <mesh geometry={nodes.Object_236.geometry} material={nodes.Object_236.material} />
          </group>
          <group position={[-0.03, 3.02, -0.01]} rotation={[0, -Math.PI / 2, 0]} scale={[0.05, 0.05, 0.05]}>
            <mesh geometry={nodes.Object_238.geometry} material={nodes.Object_238.material} />
          </group>
          <group position={[-0.05, 1.59, -0.14]} rotation={[0, -Math.PI / 2, 0]} scale={[0.03, 0.03, 0.03]}>
            <mesh geometry={nodes.Object_240.geometry} material={nodes.Object_240.material} />
          </group>
          <group position={[0.12, 1.63, -0.12]} rotation={[0, -Math.PI / 2, 0]} scale={[0.05, 0.05, 0.05]}>
            <mesh geometry={nodes.Object_242.geometry} material={nodes.Object_242.material} />
          </group>
          <group position={[-0.09, 2.66, 0.18]} rotation={[0, -Math.PI / 2, 0]} scale={[0.07, 0.07, 0.07]}>
            <mesh geometry={nodes.Object_244.geometry} material={nodes.Object_244.material} />
          </group>
          <group position={[-0.17, 2.72, -0.09]} rotation={[0, -Math.PI / 2, 0]} scale={[0.06, 0.06, 0.06]}>
            <mesh geometry={nodes.Object_246.geometry} material={nodes.Object_246.material} />
          </group>
          <group position={[-0.03, 1.82, 0.25]} rotation={[0, -Math.PI / 2, 0]} scale={[0.03, 0.03, 0.03]}>
            <mesh geometry={nodes.Object_248.geometry} material={nodes.Object_248.material} />
          </group>
          <group position={[0.15, 1.96, 0.21]} rotation={[0, -Math.PI / 2, 0]} scale={[0.07, 0.07, 0.07]}>
            <mesh geometry={nodes.Object_250.geometry} material={nodes.Object_250.material} />
          </group>
          <group position={[0, 2.89, 0.08]} rotation={[0, -Math.PI / 2, 0]} scale={[0.07, 0.07, 0.07]}>
            <mesh geometry={nodes.Object_252.geometry} material={nodes.Object_252.material} />
          </group>
          <group position={[-0.17, 2.67, -0.05]} rotation={[0, -Math.PI / 2, 0]} scale={[0.01, 0.01, 0.01]}>
            <mesh geometry={nodes.Object_254.geometry} material={nodes.Object_254.material} />
          </group>
          <group position={[-0.08, 2.34, 0.23]} rotation={[0, -Math.PI / 2, 0]} scale={[0.07, 0.07, 0.07]}>
            <mesh geometry={nodes.Object_256.geometry} material={nodes.Object_256.material} />
          </group>
          <group position={[0.16, 1.68, -0.15]} rotation={[0, -Math.PI / 2, 0]} scale={[0.07, 0.07, 0.07]}>
            <mesh geometry={nodes.Object_258.geometry} material={nodes.Object_258.material} />
          </group>
          <group position={[0.13, 1.79, -0.2]} rotation={[0, -Math.PI / 2, 0]} scale={[0.05, 0.05, 0.05]}>
            <mesh geometry={nodes.Object_260.geometry} material={nodes.Object_260.material} />
          </group>
          <group position={[-0.06, 1.4, 0.03]} rotation={[0, -Math.PI / 2, 0]} scale={[0.05, 0.05, 0.05]}>
            <mesh geometry={nodes.Object_262.geometry} material={nodes.Object_262.material} />
          </group>
          <group position={[0.15, 2.17, -0.22]} rotation={[0, -Math.PI / 2, 0]} scale={[0.07, 0.07, 0.07]}>
            <mesh geometry={nodes.Object_264.geometry} material={nodes.Object_264.material} />
          </group>
          <group position={[0.24, 1.83, 0.05]} rotation={[0, -Math.PI / 2, 0]} scale={[0.06, 0.06, 0.06]}>
            <mesh geometry={nodes.Object_266.geometry} material={nodes.Object_266.material} />
          </group>
          <group position={[-0.13, 1.62, -0.12]} rotation={[0, -Math.PI / 2, 0]} scale={[0.03, 0.03, 0.03]}>
            <mesh geometry={nodes.Object_268.geometry} material={nodes.Object_268.material} />
          </group>
          <group position={[-0.09, 1.4, 0.01]} rotation={[0, -Math.PI / 2, 0]} scale={[0.04, 0.04, 0.04]}>
            <mesh geometry={nodes.Object_270.geometry} material={nodes.Object_270.material} />
          </group>
          <group position={[-0.09, 1.77, -0.27]} rotation={[0, -Math.PI / 2, 0]} scale={[0.02, 0.02, 0.02]}>
            <mesh geometry={nodes.Object_272.geometry} material={nodes.Object_272.material} />
          </group>
          <group position={[0.09, 2.38, -0.26]} rotation={[0, -Math.PI / 2, 0]} scale={[0.02, 0.02, 0.02]}>
            <mesh geometry={nodes.Object_274.geometry} material={nodes.Object_274.material} />
          </group>
          <group position={[0.17, 1.79, -0.19]} rotation={[0, -Math.PI / 2, 0]} scale={[0.05, 0.05, 0.05]}>
            <mesh geometry={nodes.Object_276.geometry} material={nodes.Object_276.material} />
          </group>
          <group position={[-0.25, 1.84, 0.07]} rotation={[0, -Math.PI / 2, 0]} scale={[0.02, 0.02, 0.02]}>
            <mesh geometry={nodes.Object_278.geometry} material={nodes.Object_278.material} />
          </group>
          <group position={[0.16, 1.57, -0.13]} rotation={[0, -Math.PI / 2, 0]} scale={[0.06, 0.06, 0.06]}>
            <mesh geometry={nodes.Object_280.geometry} material={nodes.Object_280.material} />
          </group>
          <group position={[0.16, 1.93, -0.21]} rotation={[0, -Math.PI / 2, 0]} scale={[0.06, 0.06, 0.06]}>
            <mesh geometry={nodes.Object_282.geometry} material={nodes.Object_282.material} />
          </group>
          <group position={[-0.05, 1.59, -0.21]} rotation={[0, -Math.PI / 2, 0]} scale={[0.04, 0.04, 0.04]}>
            <mesh geometry={nodes.Object_284.geometry} material={nodes.Object_284.material} />
          </group>
          <group position={[0.13, 1.45, 0.03]} rotation={[0, -Math.PI / 2, 0]} scale={[0.07, 0.07, 0.07]}>
            <mesh geometry={nodes.Object_286.geometry} material={nodes.Object_286.material} />
          </group>
          <group position={[-0.07, 1.5, 0.16]} rotation={[0, -Math.PI / 2, 0]} scale={[0.01, 0.01, 0.01]}>
            <mesh geometry={nodes.Object_288.geometry} material={nodes.Object_288.material} />
          </group>
          <group position={[0.06, 2.68, -0.12]} rotation={[0, -Math.PI / 2, 0]} scale={[0.07, 0.07, 0.07]}>
            <mesh geometry={nodes.Object_290.geometry} material={nodes.Object_290.material} />
          </group>
          <group position={[0.23, 1.91, -0.14]} rotation={[0, -Math.PI / 2, 0]} scale={[0.02, 0.02, 0.02]}>
            <mesh geometry={nodes.Object_292.geometry} material={nodes.Object_292.material} />
          </group>
          <group position={[-0.25, 2.11, -0.03]} rotation={[0, -Math.PI / 2, 0]} scale={[0.01, 0.01, 0.01]}>
            <mesh geometry={nodes.Object_294.geometry} material={nodes.Object_294.material} />
          </group>
          <group position={[-0.1, 2.63, 0.11]} rotation={[0, -Math.PI / 2, 0]} scale={[0.07, 0.07, 0.07]}>
            <mesh geometry={nodes.Object_296.geometry} material={nodes.Object_296.material} />
          </group>
          <group position={[-0.05, 2.48, -0.2]} rotation={[0, -Math.PI / 2, 0]} scale={[0.04, 0.04, 0.04]}>
            <mesh geometry={nodes.Object_298.geometry} material={nodes.Object_298.material} />
          </group>
          <group position={[0.12, 1.96, 0.23]} rotation={[0, -Math.PI / 2, 0]} scale={[0.06, 0.06, 0.06]}>
            <mesh geometry={nodes.Object_300.geometry} material={nodes.Object_300.material} />
          </group>
          <group position={[0.21, 1.58, -0.06]} rotation={[0, -Math.PI / 2, 0]} scale={[0.02, 0.02, 0.02]}>
            <mesh geometry={nodes.Object_302.geometry} material={nodes.Object_302.material} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/alien.gltf')
