/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: JeremyW (https://sketchfab.com/JeremyW)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/spinning-ufo-ca517cda25624ad291ae086fc9c10b0d
title: Spinning UFO
*/

import React, { useRef } from 'react';
import { useGLTF, useAnimations } from '@react-three/drei';
import { useLoader } from "@react-three/fiber";
import { GLTFLoader } from "three/examples/jsm/loaders/GLTFLoader";

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials, animations } = useLoader(GLTFLoader, "./alien.gltf");
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.UFOCenter_0.geometry} material={nodes.UFOCenter_0.material} />
        <mesh geometry={nodes.UFOCenter_1.geometry} material={materials.material} />
        <group rotation={[0, 0, -0.02]}>
          <mesh geometry={nodes.UFODome_0.geometry} material={materials.green} />
        </group>
        <group rotation={[0, 0, -0.02]}>
          <mesh geometry={nodes.UFOBase_0.geometry} material={materials.black} />
          <mesh geometry={nodes.UFOBase_1.geometry} material={nodes.UFOBase_1.material} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/alien.gltf')
