/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Mehmet Kozal (https://sketchfab.com/mkozal)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/angel-16th-june-2020-363dedb3a4924670b77628d5b3b58429
title: Angel [16th June 2020]
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useControls } from "leva";

export default function Model({ ...props }) {
  const group = useRef();
  const { nodes, materials } = useGLTF("/angel.gltf");

  const AngelMaterial = useControls({
    thickness: { value: 5, min: 0, max: 20 },
    roughness: { value: 0, min: 0, max: 1, step: 0.1 },
    clearcoat: { value: 1, min: 0, max: 1, step: 0.1 },
    clearcoatRoughness: { value: 0, min: 0, max: 1, step: 0.1 },
    transmission: { value: 1, min: 0.9, max: 1, step: 0.01 },
    ior: { value: 1.25, min: 1, max: 2.3, step: 0.05 },
    envMapIntensity: { value: 25, min: 0, max: 100, step: 1 },
    color: "#ffffff",
    attenuationTint: "#ffe79e",
    attenuationDistance: { value: 0, min: 0, max: 1 },
  });

  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group position={[-1.05, 8.67, 9.13]} rotation={[1.62, 0.06, 3.14]}>
          <group rotation={[-Math.PI, 0, 0]}>
            <mesh
              geometry={nodes.Model_material0_0.geometry}
              material={nodes.Model_material0_0.material}
            >
              <meshPhysicalMaterial {...AngelMaterial} />
            </mesh>
            <mesh
              geometry={nodes.Model_material0_0_1.geometry}
              material={nodes.Model_material0_0_1.material}
            >
              <meshPhysicalMaterial {...AngelMaterial} />
            </mesh>
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/angel.gltf");
