/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: AnshiNoWara (https://sketchfab.com/AnshiNoWara)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/chat-bubble-icon-d13ff0267030497ca91742ba011b0829
title: Chat Bubble Icon
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useSpring, animated, config } from "@react-spring/three";
import { useSurprise } from "../context/AboutContext";
import Mail from "./Mail";

export default function Model({ ...props }) {
  const group = useRef();
  const chat = useRef();
  const { nodes, materials } = useGLTF("/chat.gltf");
  const bugSurprise = useSurprise();

  const { scale } = useSpring({
    scale: bugSurprise ? [0.7, 0.7, 0.7] : [0, 0, 0],
    config: {duration: 200, mass: 1, tension: 180, friction: 12 }
  });
  return (
    <animated.mesh 
      ref={group}
      position={[5.8, 5.8, -0.9]}
      scale={scale}
      rotation={[0, 2, 0]}
      {...props}
      dispose={null}
    >
      <group rotation={[-Math.PI / 2, 0, 0]}>
        {/* <mesh geometry={nodes.mesh_0.geometry} material={materials['Material.001']} /> */}
        <Mail position={[-0.04, -0.49, 0.25]} scale={0.3} rotation={[1.75,0,0]}/>
        <mesh
          geometry={nodes.mesh_1.geometry}
          material={materials["Material.002"]}
          ref={chat}
          material-color = {'#B22222'}
        />
        {/* <mesh geometry={nodes.mesh_2.geometry} material={materials['Material.003']} /> */}
      </group>
    </animated.mesh>
  );
}

useGLTF.preload("/chat.gltf");
