/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: KattyLi (https://sketchfab.com/KattyLi)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/farm-1864c4ab0d5242d1b83ba947601cbb12
title: Farm
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/farm.gltf')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.21}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[0.39, 0.71, 2.97]} rotation={[0.2, -0.02, 0.42]}>
            <mesh
              geometry={nodes.animationpolySurface56_animationsheep_0.geometry}
              material={nodes.animationpolySurface56_animationsheep_0.material}
            />
          </group>
          <group name="group1" position={[0.14, 3.08, 3.36]} rotation={[3.11, 1.17, -3.11]}>
            <group position={[0.05, -0.35, -0.05]} rotation={[0, 0.13, 0]} scale={[0.37, 0.18, 0.37]}>
              <mesh
                geometry={nodes.animationpolySurface43_animationlambert3_0.geometry}
                material={materials.animationlambert3}
              />
            </group>
            <group rotation={[-0.06, 0.02, -0.28]}>
              <mesh
                geometry={nodes.animationpolySurface42_animationsheep_0.geometry}
                material={nodes.animationpolySurface42_animationsheep_0.material}
              />
            </group>
          </group>
          <group position={[0, 0, 0.1]}>
            <mesh
              geometry={nodes.animationlp_33_animationother_0.geometry}
              material={nodes.animationlp_33_animationother_0.material}
            />
          </group>
          <mesh
            geometry={nodes.animationlp_32_animationother_0.geometry}
            material={nodes.animationlp_32_animationother_0.material}
          />
          <mesh
            geometry={nodes.animationlp_31_animationother_0.geometry}
            material={nodes.animationlp_31_animationother_0.material}
          />
          <mesh
            geometry={nodes.animationlp_30_animationother_0.geometry}
            material={nodes.animationlp_30_animationother_0.material}
          />
          <mesh
            geometry={nodes.animationlp_22_animationother_0.geometry}
            material={nodes.animationlp_22_animationother_0.material}
          />
          <mesh
            geometry={nodes.animationlp_20_animationother_0.geometry}
            material={nodes.animationlp_20_animationother_0.material}
          />
          <mesh
            geometry={nodes.animationlp_19_animationhouse_0.geometry}
            material={nodes.animationlp_19_animationhouse_0.material}
          />
          <mesh
            geometry={nodes.animationlp_18_animationother_0.geometry}
            material={nodes.animationlp_18_animationother_0.material}
          />
          <mesh
            geometry={nodes.animationlp_17_animationhouse_0.geometry}
            material={nodes.animationlp_17_animationhouse_0.material}
          />
          <mesh
            geometry={nodes.animationlp_16_animationhouse_0.geometry}
            material={nodes.animationlp_16_animationhouse_0.material}
          />
          <mesh
            geometry={nodes.animationlp_15_animationhouse_0.geometry}
            material={nodes.animationlp_15_animationhouse_0.material}
          />
          <mesh
            geometry={nodes.animationlp_14_animationhouse_0.geometry}
            material={nodes.animationlp_14_animationhouse_0.material}
          />
          <mesh
            geometry={nodes.animationlp_13_animationhouse_0.geometry}
            material={nodes.animationlp_13_animationhouse_0.material}
          />
          <mesh
            geometry={nodes.animationlp_12_animationhouse_0.geometry}
            material={nodes.animationlp_12_animationhouse_0.material}
          />
          <mesh
            geometry={nodes.animationlp_3_animationhouse_0.geometry}
            material={nodes.animationlp_3_animationhouse_0.material}
          />
          <mesh
            geometry={nodes.animationlp_2_animationhouse_0.geometry}
            material={nodes.animationlp_2_animationhouse_0.material}
          />
          <mesh
            geometry={nodes.animationlp_1_animationhouse_0.geometry}
            material={nodes.animationlp_1_animationhouse_0.material}
          />
          <group position={[0, -0.44, 0.32]}>
            <mesh
              geometry={nodes.animationlp_60_animationother_0.geometry}
              material={nodes.animationlp_60_animationother_0.material}
            />
          </group>
          <group position={[0, -0.44, -0.19]}>
            <mesh
              geometry={nodes.animationlp_61_animationother_0.geometry}
              material={nodes.animationlp_61_animationother_0.material}
            />
          </group>
          <group position={[-0.7, 0, -0.6]} rotation={[0, 0.46, 0]}>
            <mesh
              geometry={nodes.animationlp_62_animationother_0.geometry}
              material={nodes.animationlp_62_animationother_0.material}
            />
          </group>
          <group position={[-0.83, 0, -2.82]} rotation={[0, -0.54, 0]}>
            <mesh
              geometry={nodes.animationlp_63_animationother_0.geometry}
              material={nodes.animationlp_63_animationother_0.material}
            />
          </group>
          <group position={[-1.93, 0.08, -1.72]} rotation={[0, -0.27, 0]} scale={0.93}>
            <mesh
              geometry={nodes.animationlp_64_animationother_0.geometry}
              material={nodes.animationlp_64_animationother_0.material}
            />
          </group>
          <group position={[-2.62, 0.08, 0]} rotation={[0, 0.01, 0]} scale={0.93}>
            <mesh
              geometry={nodes.animationlp_65_animationother_0.geometry}
              material={nodes.animationlp_65_animationother_0.material}
            />
          </group>
          <group position={[-3.13, 0.01, -2.94]} rotation={[0, -0.77, 0]}>
            <mesh
              geometry={nodes.animationlp_73_animationother_0.geometry}
              material={nodes.animationlp_73_animationother_0.material}
            />
          </group>
          <group position={[-2.92, 0, 0.26]} rotation={[0, 0.34, 0]}>
            <mesh
              geometry={nodes.animationlp_74_animationother_0.geometry}
              material={nodes.animationlp_74_animationother_0.material}
            />
          </group>
          <group position={[-2.95, 0, -0.22]}>
            <mesh
              geometry={nodes.animationlp_75_animationother_0.geometry}
              material={nodes.animationlp_75_animationother_0.material}
            />
          </group>
          <group position={[-4.71, 0, -0.84]} rotation={[0, -0.82, 0]}>
            <mesh
              geometry={nodes.animationlp_76_animationother_0.geometry}
              material={nodes.animationlp_76_animationother_0.material}
            />
          </group>
          <group position={[-4.71, 0, -2.32]} rotation={[0, -0.54, 0]}>
            <mesh
              geometry={nodes.animationlp_77_animationother_0.geometry}
              material={nodes.animationlp_77_animationother_0.material}
            />
          </group>
          <group position={[-5.03, 0, -0.35]} rotation={[0, -0.82, 0]}>
            <mesh
              geometry={nodes.animationlp_78_animationother_0.geometry}
              material={nodes.animationlp_78_animationother_0.material}
            />
          </group>
          <group position={[-4.22, 0, 0.81]} rotation={[0, -0.18, 0]}>
            <mesh
              geometry={nodes.animationlp_79_animationother_0.geometry}
              material={nodes.animationlp_79_animationother_0.material}
            />
          </group>
          <group position={[-4.4, 0, -0.03]} rotation={[0, -0.22, 0]}>
            <mesh
              geometry={nodes.animationlp_80_animationother_0.geometry}
              material={nodes.animationlp_80_animationother_0.material}
            />
          </group>
          <group position={[0.1, -0.15, -1.4]} rotation={[0, -0.69, 0]}>
            <mesh
              geometry={nodes.animationlp_82_animationsheep_0.geometry}
              material={nodes.animationlp_82_animationsheep_0.material}
            />
          </group>
          <group position={[-2.76, -0.3, -0.84]} rotation={[0, 0.35, 0]} scale={1.23}>
            <mesh
              geometry={nodes.animationlp_83_animationsheep_0.geometry}
              material={nodes.animationlp_83_animationsheep_0.material}
            />
          </group>
          <group position={[-0.14, -0.15, -0.58]} rotation={[0, -0.91, 0]}>
            <mesh
              geometry={nodes.animationlp_84_animationsheep_0.geometry}
              material={nodes.animationlp_84_animationsheep_0.material}
            />
          </group>
          <group position={[-2.24, -0.04, -0.53]} rotation={[0, 0.35, 0]} scale={0.84}>
            <mesh
              geometry={nodes.animationlp_85_animationsheep_0.geometry}
              material={nodes.animationlp_85_animationsheep_0.material}
            />
          </group>
          <group position={[-3.24, -0.04, 2.77]} rotation={[0, 1.49, 0]} scale={0.84}>
            <mesh
              geometry={nodes.animationlp_86_animationsheep_0.geometry}
              material={nodes.animationlp_86_animationsheep_0.material}
            />
          </group>
          <group position={[2.12, 0.1, 0.87]} rotation={[0, -0.84, 0]} scale={0.64}>
            <mesh
              geometry={nodes.animationlp_87_animationsheep_0.geometry}
              material={nodes.animationlp_87_animationsheep_0.material}
            />
          </group>
          <group position={[0.08, 0.1, 0.76]} rotation={[0, 0.29, 0]} scale={0.64}>
            <mesh
              geometry={nodes.animationlp_88_animationsheep_0.geometry}
              material={nodes.animationlp_88_animationsheep_0.material}
            />
          </group>
          <group position={[-3.35, -0.15, 1.77]} rotation={[0, 1.38, 0]}>
            <mesh
              geometry={nodes.animationlp_89_animationsheep_0.geometry}
              material={nodes.animationlp_89_animationsheep_0.material}
            />
          </group>
          <group position={[-2.7, -0.15, 3.07]} rotation={[-Math.PI, 1.3, -Math.PI]}>
            <mesh
              geometry={nodes.animationlp_90_animationsheep_0.geometry}
              material={nodes.animationlp_90_animationsheep_0.material}
            />
          </group>
          <mesh
            geometry={nodes.animationlp_10_animationother_0.geometry}
            material={nodes.animationlp_10_animationother_0.material}
          />
          <group position={[-0.11, 0, -0.04]} rotation={[0, -0.5, 0]}>
            <mesh
              geometry={nodes.animationlp_66_animationother_0.geometry}
              material={nodes.animationlp_66_animationother_0.material}
            />
          </group>
          <group position={[-0.11, 0, -0.12]} rotation={[0, -1.02, 0]}>
            <mesh
              geometry={nodes.animationlp_67_animationother_0.geometry}
              material={nodes.animationlp_67_animationother_0.material}
            />
          </group>
          <group position={[-0.02, 0, -0.07]} rotation={[0, -1.56, 0]}>
            <mesh
              geometry={nodes.animationlp_68_animationother_0.geometry}
              material={nodes.animationlp_68_animationother_0.material}
            />
          </group>
          <group position={[-2.68, 0, 3.57]} rotation={[-Math.PI, 0.29, -Math.PI]}>
            <mesh
              geometry={nodes.animationlp_69_animationother_0.geometry}
              material={nodes.animationlp_69_animationother_0.material}
            />
          </group>
          <group position={[-0.8, 0, 3.63]} rotation={[-Math.PI, 0.29, -Math.PI]}>
            <mesh
              geometry={nodes.animationpolySurface1_animationother_0.geometry}
              material={nodes.animationpolySurface1_animationother_0.material}
            />
            <mesh
              geometry={nodes.animationpolySurface6_animationother_0.geometry}
              material={nodes.animationpolySurface6_animationother_0.material}
            />
            <mesh
              geometry={nodes.animationpolySurface7_animationother_0.geometry}
              material={nodes.animationpolySurface7_animationother_0.material}
            />
            <mesh
              geometry={nodes.animationpolySurface8_animationother_0.geometry}
              material={nodes.animationpolySurface8_animationother_0.material}
            />
          </group>
          <group position={[-1.82, 0, 2.75]} rotation={[0, 1.44, 0]}>
            <mesh
              geometry={nodes.animationlp_71_animationother_0.geometry}
              material={nodes.animationlp_71_animationother_0.material}
            />
          </group>
          <group position={[-1.99, 0, 0.94]} rotation={[0, 1.44, 0]}>
            <mesh
              geometry={nodes.animationpolySurface11_animationother_0.geometry}
              material={nodes.animationpolySurface11_animationother_0.material}
            />
          </group>
          <group position={[1.01, -0.78, 0.03]}>
            <mesh
              geometry={nodes.animationpolySurface77_animationother_0.geometry}
              material={nodes.animationpolySurface77_animationother_0.material}
            />
            <group position={[0.02, 0, 0]}>
              <mesh
                geometry={nodes.animationpolySurface78_animationother_0.geometry}
                material={nodes.animationpolySurface78_animationother_0.material}
              />
            </group>
          </group>
          <group position={[-0.21, 0, 0.02]} rotation={[0, -0.16, 0]}>
            <mesh
              geometry={nodes.animationlp_81_animationother_0.geometry}
              material={nodes.animationlp_81_animationother_0.material}
            />
          </group>
          <group position={[-2.68, 0.77, 3.57]} rotation={[-Math.PI, 0.29, -Math.PI]}>
            <group position={[-0.91, -0.77, 0.24]}>
              <mesh
                geometry={nodes.animationpolySurface85_animationother_0.geometry}
                material={nodes.animationpolySurface85_animationother_0.material}
              />
            </group>
          </group>
          <group position={[-1.82, 0, -0.1]} rotation={[0, 1.15, 0]}>
            <mesh
              geometry={nodes.animationpolySurface90_animationother_0.geometry}
              material={nodes.animationpolySurface90_animationother_0.material}
            />
          </group>
          <mesh
            geometry={nodes.animationpolySurface95_animationother_0.geometry}
            material={nodes.animationpolySurface95_animationother_0.material}
          />
          <mesh
            geometry={nodes.animationpolySurface97_animationother_0.geometry}
            material={nodes.animationpolySurface97_animationother_0.material}
          />
          <group position={[-0.2, 0, 1.2]}>
            <mesh
              geometry={nodes.animationpolySurface98_animationother_0.geometry}
              material={nodes.animationpolySurface98_animationother_0.material}
            />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/farm.gltf')
