/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: KattyLi (https://sketchfab.com/KattyLi)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/farm-1864c4ab0d5242d1b83ba947601cbb12
title: Farm
*/

import React, { useEffect } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export default function Model({ ...props }) {
  const { scene, animations } = useGLTF('/farm.gltf')
  const { ref, actions } = useAnimations(animations)

  useEffect(() => {
    actions["Take 001"].play();
  }, [actions]);
  
  return (
    <primitive object={scene} ref={ref} position={[-1.3, -20, -2]} {...props}/>
  )
}

useGLTF.preload('/farm.gltf')
