/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Thomas Flynn (https://sketchfab.com/nebulousflynn)
license: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
source: https://sketchfab.com/3d-models/daisy-0e67b47e44f64d5bbcfc174329cb2217
title: Daisy
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/grass.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group scale={151.37}>
          <group position={[-4.64, -4.64, -0.58]}>
            <points geometry={nodes.mesh_0.geometry} material={nodes.mesh_0.material} />
            <points geometry={nodes.mesh_1.geometry} material={nodes.mesh_1.material} />
            <points geometry={nodes.mesh_2.geometry} material={nodes.mesh_2.material} />
            <points geometry={nodes.mesh_3.geometry} material={nodes.mesh_3.material} />
            <points geometry={nodes.mesh_4.geometry} material={nodes.mesh_4.material} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/grass.gltf')
