/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: PhantomXD (https://sketchfab.com/PhantomXD)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/old-gmail-logo-f8c066b10d1a475abbd69ebbe9de2b83
title: Old Gmail Logo
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useSurprise } from "../context/AboutContext";
import { useFrame } from "@react-three/fiber";

export default function Model({ ...props }) {
  const ref = useRef();
  const { nodes, materials } = useGLTF("/mail.gltf");
  const bugSurprise = useSurprise();

  useFrame(() => {
    if (bugSurprise) {
      ref.current.visible = true;
    } else {
      ref.current.visible = false;
    }
  });

  return (
    <mesh
      ref={ref}
      scale={0.35}
      {...props}
      dispose={null}
    >
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group
          position={[0, 0, -0.07]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={[1.22, 1.05, 1.22]}
        >
          <mesh
            geometry={nodes.Plane_0.geometry}
            material={nodes.Plane_0.material}
          />
          <mesh
            geometry={nodes.Plane_1.geometry}
            material={materials["Material.002"]}
          />
        </group>
        <group
          position={[0, -0.14, 0]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={[1.4, 1.36, 1.36]}
        >
          <mesh
            geometry={nodes.Plane001_0.geometry}
            material={nodes.Plane001_0.material}
          />
        </group>
      </group>
    </mesh>
  );
}

useGLTF.preload("/mail.gltf");
