/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Jakob Henerey (https://sketchfab.com/hellonintendo8)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/models/7b62dae60f2c4443b9f499c833171ca5
title: Arrow
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";

export default function Model({ ...props }) {
  const ref = useRef();
  const { scene, materials } = useGLTF("/pointer.gltf");

  useFrame(({clock}) => {
    ref.current.position.y = 6.5 + (Math.sin(clock.getElapsedTime()*4)/4);
    ref.current.rotation.z = Math.sin(clock.getElapsedTime() / 10) * 3.5 * Math.PI

    // if (modelInView && !bugSurprise) {
    //   ref.current.visible = true;
    // } else {
    //   ref.current.visible = false;
    // }
  });

  return (
    <primitive
      ref={ref}
      object={scene}
      position={[4.2, 8.5, 1.75]}
      material={materials.arrow}
      material-metalness={1}
      material-color={[192,192,192]}
      scale={0.08}
      rotation={[1.8, 0, Math.PI / 2]}
    />
  );

}

useGLTF.preload("/pointer.gltf");
