/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Diego G. (https://sketchfab.com/empty_mirror)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/keyboardist-robot-1510292849ab4f5d9de37a01645c47a7
title: Keyboardist Robot
*/

import React, { useRef, useEffect } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";
import Terminal from "./Terminal";
import { useFrame } from "@react-three/fiber";

export default function Model({ ...props }) {
  const robotTerminalRef = useRef();
  const { scene, animations } = useGLTF("/robot.gltf");
  const { ref, actions } = useAnimations(animations);

  useEffect(() => {
    actions["Scene"].play();
  }, [actions]);

  useFrame(({clock}) => {
    robotTerminalRef.current.position.y =  Math.sin(clock.getElapsedTime()*4)/3;
  });

  return (
    <mesh ref={robotTerminalRef} position={[-1,-1,0]} >
      <Terminal position={[3.1, -41, -1]} rotation={[-1.2,-0.9,-1]} scale={[0.06, 0.05,0.05]}/>
      <primitive
        object={scene}
        position={[0, -45, 0]}
        rotation={[0,1.9,0]}
        scale={0.005}
        ref={ref}
        {...props}
      />
    </mesh>
    
  );
}

useGLTF.preload("/robot.gltf");
