/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: loarziel_ (https://sketchfab.com/loarziel_)
license: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
source: https://sketchfab.com/3d-models/sci-fi-screen-3d-model-d4dbce94be204718a58878c349db5dfa
title: Sci-Fi Screen - 3D Model
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { scene } = useGLTF('/terminal.gltf')
  return (
    <primitive ref={group} object={scene} {...props} dispose={null}/>
  )
}

useGLTF.preload('/terminal.gltf')
