/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: loarziel_ (https://sketchfab.com/loarziel_)
license: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
source: https://sketchfab.com/3d-models/sci-fi-screen-3d-model-d4dbce94be204718a58878c349db5dfa
title: Sci-Fi Screen - 3D Model
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/terminal.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group rotation={[-Math.PI / 2, 0, 0]}>
            <group position={[-0.04, -3.84, -18.28]}>
              <mesh geometry={nodes.marco__0.geometry} material={materials['Scene_-_Root']} />
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/terminal.gltf')
