/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Ale_jandro (https://sketchfab.com/Ale_jandro)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/floating-island-handpainted-fe1de0e8e12649518f0c3ea2b804dca8
title: Floating_island_HandPainted
*/
import * as THREE from "three";
import React, { useEffect, useState, useRef} from "react";
import { useGLTF, useAnimations, useScroll } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";

export default function Model({ ...props }) {
  const { nodes, materials, animations } = useGLTF("/tree.gltf");
  const { ref, actions } = useAnimations(animations);
  const scroll = useScroll();
  const [hovered, setHovered] = useState(false);

  useEffect(() => {
    actions["Take 001"].play();
  }, [actions]);

  useFrame((state, delta) => {
    const offset = 1 - scroll.offset;
    state.camera.position.set(
      Math.sin(offset) * 30,
      Math.atan(offset * Math.PI * 2) * 5,
      Math.cos((offset * Math.PI) / 3) * -10
    );
    state.camera.lookAt(0, 9, 9);

    ref.current.position.x = 0;
    ref.current.position.y = -15;
    ref.current.position.z = 3;

    if (hovered) {
    }
  });

  return (
    <group ref={ref} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[0.16, 4.38, 0]} scale={[0.87, 0.88, 0.88]}>
            <mesh
              geometry={nodes.plataforma1_lambert5_0.geometry}
              material={materials.lambert5}
            />
          </group>
          <group
            position={[2.71, 3.55, 0.53]}
            rotation={[-0.51, -1.01, -0.67]}
            scale={0.35}
          >
            <mesh
              geometry={nodes.polySurface38_lambert7_0.geometry}
              material={nodes.polySurface38_lambert7_0.material}
            />
          </group>
          <group
            position={[1.59, 4, 0.34]}
            rotation={[-3.09, 0.1, -2.8]}
            scale={0.35}
          >
            <mesh
              geometry={nodes.polySurface37_lambert7_0.geometry}
              material={nodes.polySurface37_lambert7_0.material}
            />
          </group>
          <group
            position={[0.76, 3.64, 2.02]}
            rotation={[-2.8, 0.11, 3.1]}
            scale={0.35}
          >
            <mesh
              geometry={nodes.polySurface36_lambert7_0.geometry}
              material={nodes.polySurface36_lambert7_0.material}
            />
          </group>
          <group
            position={[0.82, 3.22, 1.2]}
            rotation={[-2.55, 0.1, 3.08]}
            scale={0.46}
          >
            <mesh
              geometry={nodes.polySurface35_lambert7_0.geometry}
              material={nodes.polySurface35_lambert7_0.material}
            />
          </group>
          <group
            position={[-2.3, 6.19, 0.38]}
            rotation={[-0.01, 1.04, 0.1]}
            scale={[0.32, 0.6, 0.02]}
          >
            <mesh
              geometry={nodes.pCube5_lambert7_0.geometry}
              material={nodes.pCube5_lambert7_0.material}
            />
          </group>
          <group
            position={[-2.42, 6.23, -0.1]}
            rotation={[3.03, -0.96, 2.9]}
            scale={[0.52, 0.99, 0.19]}
          >
            <mesh
              geometry={nodes.pCube3_lambert14_0.geometry}
              material={materials.lambert14}
            />
          </group>
          <group
            position={[1.42, 2, 0.78]}
            rotation={[-Math.PI, 0.12, -Math.PI]}
            scale={0.64}
          >
            <mesh
              geometry={nodes.polySurface34_lambert7_0.geometry}
              material={nodes.polySurface34_lambert7_0.material}
            />
          </group>
          <group
            position={[0.17, -4.28, 3.1]}
            rotation={[-Math.PI, -1.48, -Math.PI]}
            scale={1.77}
          >
            <mesh
              geometry={nodes.polySurface33_lambert7_0.geometry}
              material={nodes.polySurface33_lambert7_0.material}
            />
          </group>
          <group position={[0, 0, -1.11]}>
            <mesh
              geometry={nodes.polySurface32_lambert7_0.geometry}
              material={nodes.polySurface32_lambert7_0.material}
            />
          </group>
          <group
            position={[-0.32, 3.62, 2.31]}
            rotation={[0.27, -0.11, -3.11]}
            scale={-0.35}
          >
            <mesh
              geometry={nodes.polySurface39_lambert7_0.geometry}
              material={nodes.polySurface39_lambert7_0.material}
            />
          </group>
          <group
            position={[-2.27, 3.68, 2.22]}
            rotation={[3.1, 0.12, -3.14]}
            scale={0.35}
          >
            <mesh
              geometry={nodes.polySurface40_lambert7_0.geometry}
              material={nodes.polySurface40_lambert7_0.material}
            />
          </group>
          <group
            position={[1.03, 3.9, 1.6]}
            rotation={[0.72, -0.09, -3.07]}
            scale={-0.35}
          >
            <mesh
              geometry={nodes.polySurface41_lambert7_0.geometry}
              material={nodes.polySurface41_lambert7_0.material}
            />
          </group>
          <group
            position={[1.01, 6.56, -1.35]}
            rotation={[-Math.PI, 0, -0.03]}
            scale={[-0.47, -0.88, -0.02]}
          >
            <mesh
              geometry={nodes.pCube6_lambert7_0.geometry}
              material={nodes.pCube6_lambert7_0.material}
            />
          </group>
          <group
            position={[1.97, 6.73, -1.21]}
            rotation={[0, 0, -0.3]}
            scale={[0.59, 1.12, 0.03]}
          >
            <mesh
              geometry={nodes.pCube7_Default_Material_0.geometry}
              material={materials.Default_Material}
            />
          </group>
          <group
            position={[2.51, 6.12, -1.19]}
            rotation={[2.85, -0.09, 0.42]}
            scale={[-0.28, -0.53, -0.01]}
          >
            <mesh
              geometry={nodes.pCube8_lambert7_0.geometry}
              material={nodes.pCube8_lambert7_0.material}
            />
          </group>
          <group
            position={[-1.53, 6.35, -0.86]}
            rotation={[-0.21, 0.22, 0.1]}
            scale={[0.37, 0.7, 0.02]}
          >
            <mesh
              geometry={nodes.pCube9_lambert7_0.geometry}
              material={nodes.pCube9_lambert7_0.material}
            />
          </group>
          <group
            position={[-2.26, 6.73, -1.21]}
            rotation={[2.66, -0.43, -0.24]}
            scale={[-0.59, -1.12, -0.03]}
          >
            <mesh
              geometry={nodes.pCube10_lambert7_0.geometry}
              material={nodes.pCube10_lambert7_0.material}
            />
          </group>
          <group
            position={[-2.06, 5.91, 0.84]}
            rotation={[0.42, -1.24, 0.38]}
            scale={[0.2, 0.38, 0.07]}
          >
            <mesh
              geometry={nodes.pCube12_lambert7_0.geometry}
              material={nodes.pCube12_lambert7_0.material}
            />
          </group>
          <group
            position={[2.25, 6, -1.47]}
            rotation={[-0.57, -0.88, 2.67]}
            scale={[-0.35, -0.67, -0.13]}
          >
            <mesh
              geometry={nodes.pCube13_lambert7_0.geometry}
              material={nodes.pCube13_lambert7_0.material}
            />
          </group>
          <group
            position={[-1.29, 1.75, -0.42]}
            rotation={[0, -1.25, 0]}
            scale={[0.2, 1.15, 0.37]}
          >
            <mesh
              geometry={nodes.pPlatonic10_lambert8_0.geometry}
              material={nodes.pPlatonic10_lambert8_0.material}
            />
          </group>
          <group
            position={[1.05, -1.11, -1.8]}
            rotation={[-Math.PI, -1.46, -Math.PI]}
            scale={[0.36, 2.01, 0.66]}
          >
            <mesh
              geometry={nodes.pPlatonic9_lambert8_0.geometry}
              material={nodes.pPlatonic9_lambert8_0.material}
            />
          </group>
          <group position={[-0.65, 6.03, 1.4]} scale={[0.21, 0.39, 0.27]}>
            <mesh
              geometry={nodes.pPlatonic8_lambert8_0.geometry}
              material={nodes.pPlatonic8_lambert8_0.material}
            />
          </group>
          <group
            position={[1.24, 5.85, 0.96]}
            rotation={[0, -1.55, 0]}
            scale={[0.17, 0.17, 0.29]}
          >
            <mesh
              geometry={nodes.pPlatonic7_lambert8_0.geometry}
              material={nodes.pPlatonic7_lambert8_0.material}
            />
          </group>
          <group
            position={[0.76, 6.02, 1.14]}
            rotation={[-0.13, -0.83, -0.21]}
            scale={[0.35, 0.6, 0.35]}
          >
            <mesh
              geometry={nodes.pPlatonic6_lambert8_0.geometry}
              material={nodes.pPlatonic6_lambert8_0.material}
            />
          </group>
          <group
            position={[-0.37, 5.82, 1.77]}
            rotation={[-Math.PI, -0.97, -Math.PI]}
            scale={[0.12, 0.12, 0.21]}
          >
            <mesh
              geometry={nodes.pPlatonic5_lambert8_0.geometry}
              material={nodes.pPlatonic5_lambert8_0.material}
            />
          </group>
          <group position={[0.04, 6.02, 1.35]} scale={[0.6, 1.03, 0.6]}>
            <mesh
              geometry={nodes.pPlatonic4_lambert8_0.geometry}
              material={nodes.pPlatonic4_lambert8_0.material}
            />
          </group>
          <group
            position={[1.76, 5.85, 1.03]}
            rotation={[0, -0.82, 0]}
            scale={[0.18, 0.18, 0.31]}
          >
            <mesh
              geometry={nodes.pPlatonic3_lambert8_0.geometry}
              material={nodes.pPlatonic3_lambert8_0.material}
            />
          </group>
          <group position={[1.59, 6.03, 0.78]} scale={[0.21, 0.39, 0.27]}>
            <mesh
              geometry={nodes.pPlatonic2_lambert8_0.geometry}
              material={nodes.pPlatonic2_lambert8_0.material}
            />
          </group>
          <group
            position={[2.11, 5.92, 0.45]}
            rotation={[0, -0.82, 0]}
            scale={[0.31, 0.31, 0.53]}
          >
            <mesh
              geometry={nodes.pPlatonic1_lambert8_0.geometry}
              material={nodes.pPlatonic1_lambert8_0.material}
            />
          </group>
          <group
            position={[0.38, 11.97, 0.01]}
            rotation={[-0.24, 0, 0]}
            scale={1.21}
          >
            <mesh
              geometry={nodes.pPlatonic11_lambert3_0.geometry}
              material={materials.lambert3}
            />
          </group>
          <group
            position={[-2.44, 13.04, 0.48]}
            rotation={[-0.17, 0, 0]}
            scale={1.54}
          >
            <mesh
              geometry={nodes.pPlatonic12_lambert2_0.geometry}
              material={materials.lambert2}
            />
          </group>
          <group
            position={[-2.43, 10.31, 1.31]}
            rotation={[1.66, 0, -0.26]}
            scale={[1.27, 0.8, 0.8]}
          >
            <mesh
              geometry={nodes.pPlatonic13_lambert1_0.geometry}
              material={nodes.pPlatonic13_lambert1_0.material}
            />
          </group>
          <group
            position={[0.48, 10.16, 0.63]}
            rotation={[-0.4, 0.26, 0]}
            scale={0.73}
          >
            <mesh
              geometry={nodes.pPlatonic14_lambert1_0.geometry}
              material={nodes.pPlatonic14_lambert1_0.material}
            />
          </group>
          <mesh
            geometry={nodes.arbol1_lambert4_0.geometry}
            material={materials.lambert4}
          />
          <group
            position={[1.07, 2.88, 4.29]}
            rotation={[-0.82, 1.12, 0.72]}
            scale={[0.29, 0.29, 0.29]}
          >
            <mesh
              geometry={nodes.baculo__lambert9_0.geometry}
              material={materials.lambert9}
            />
          </group>
          <group position={[0.44, 7.73, 1.41]} scale={0.03}>
            <mesh
              geometry={nodes.pSphere8_lambert13_0.geometry}
              material={nodes.pSphere8_lambert13_0.material}
            />
          </group>
          <group position={[0.58, 7.81, 1.72]} scale={0.03}>
            <mesh
              geometry={nodes.pSphere9_lambert13_0.geometry}
              material={nodes.pSphere9_lambert13_0.material}
            />
          </group>
          <group position={[0.32, 7.72, 1.51]} scale={0.03}>
            <mesh
              geometry={nodes.pSphere10_lambert13_0.geometry}
              material={nodes.pSphere10_lambert13_0.material}
            />
          </group>
          <group position={[0.47, 7.54, 1.51]} scale={0.01}>
            <mesh
              geometry={nodes.pSphere11_lambert13_0.geometry}
              material={nodes.pSphere11_lambert13_0.material}
            />
          </group>
          <group position={[0.2, 7.84, 1.71]} scale={0.01}>
            <mesh
              geometry={nodes.pSphere12_lambert13_0.geometry}
              material={nodes.pSphere12_lambert13_0.material}
            />
          </group>
          <group position={[-0.44, 7.59, 1.2]} scale={0.02}>
            <mesh
              geometry={nodes.pSphere13_lambert13_0.geometry}
              material={nodes.pSphere13_lambert13_0.material}
            />
          </group>
          <group name="pSphere14" position={[0.31, 7.46, 1.81]} scale={0.01}>
            <mesh
              geometry={nodes.pSphere14_lambert13_0.geometry}
              material={nodes.pSphere14_lambert13_0.material}
            />
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/tree.gltf");
